# Generated by Django 6.0.4 on 2026-04-26 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0005_producto_stockminimo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id_inven', models.AutoField(primary_key=True, serialize=False)),
                ('stock_actual', models.IntegerField()),
                ('tipoUnidad', models.CharField(max_length=50)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventarios', to='productos.producto')),
            ],
        ),
    ]
