# Generated by Django 6.0.4 on 2026-05-05 00:08

from django.db import migrations


def create_default_Rols(apps, schema_editor):
    
    Rol = apps.get_model('usuarios', 'Rol')
    
    Rol.objects.bulk_create([
        Rol(nom_rol='administrador'),
        Rol(nom_rol='cajero'),
    ], ignore_conflicts=True)  # Evita error si ya existen

class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]
    operations = [
        migrations.RunPython(create_default_Rols),
    ]


