# Generated by Django 6.0.4 on 2026-04-21 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='nomCategoria',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
