# Generated by Django 6.0.4 on 2026-04-21 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ['nomProducto'], 'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='stock',
            new_name='stockActual',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='actualizado_en',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='creado_en',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='precio_compra',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='precio_venta',
        ),
        migrations.AddField(
            model_name='producto',
            name='codProducto',
            field=models.CharField(max_length=45, null=True, unique=True, verbose_name='Código de Producto'),
        ),
        migrations.AddField(
            model_name='producto',
            name='nomProducto',
            field=models.CharField(default='Producto sin nombre', max_length=100, verbose_name='Nombre del Producto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='precioCompra',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Precio de Compra'),
        ),
        migrations.AddField(
            model_name='producto',
            name='precioVenta',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Precio de Venta'),
        ),
        migrations.AddField(
            model_name='producto',
            name='tipoUnidad',
            field=models.CharField(default='unidad', max_length=100, verbose_name='Unidad De Medición del Producto'),
        ),
        migrations.AlterModelTable(
            name='producto',
            table='productos',
        ),
    ]
