# Generated by Django 6.0.4 on 2026-04-26 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_producto_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='stockMinimo',
            field=models.IntegerField(default=0),
        ),
    ]
