# Generated by Django 6.0.4 on 2026-05-05 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_producto_stockminimo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='stockActual',
        ),
    ]
