# Generated by Django 6.0.4 on 2026-04-26 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('id_met_pago', models.AutoField(primary_key=True, serialize=False)),
                ('tipoPago', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('razonSocial', models.CharField(blank=True, max_length=150, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=20)),
                ('zona', models.CharField(max_length=100)),
                ('calle', models.CharField(max_length=100)),
                ('numeroCasa', models.CharField(max_length=20)),
                ('estado', models.BooleanField(default=True)),
                ('metodo_pago', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes', to='clientes.metodopago')),
            ],
        ),
    ]
