# Generated by Django 6.0.4 on 2026-04-26 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='metodo_pago',
        ),
        migrations.AddField(
            model_name='cliente',
            name='carnet',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='MetodoPago',
        ),
    ]
