# Generated by Django 6.0.4 on 2026-05-05 00:20
#cliente default cuando no hay nit o eso
from django.db import migrations

def create_default_cliente(apps, schema_editor):
    
    Cliente = apps.get_model('clientes', 'Cliente')
    
    Cliente.objects.get_or_create(
        nombre='Cliente General',
        defaults={
            'razonSocial': None,
            'carnet': None,
            'email': 'sin.registro@predeterminado.local',
            'telefono': '00000000',
            'zona': 'N/A',
            'calle': 'N/A',
            'numeroCasa': 'N/A',
            'estado': True
        }
    )

class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_remove_cliente_metodo_pago_cliente_carnet_and_more'),
    ]

    operations = [
        migrations.RunPython(create_default_cliente),
    ]