# Generated by Django 6.0.4 on 2026-05-07 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0003_alter_compra_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallecompra',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
            preserve_default=False,
        ),
    ]
